---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-test-lb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-test-lb
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx-test-lb
    spec:
      containers:
      - name: nginx-test-lb
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-lb
  namespace: default
  labels:
    app: nginx-test-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-test-lb
  type: LoadBalancer
