version: 2.1

orbs:
  codacy: codacy/base@12.1.3

references:
  circleci_job: &circleci_job
    docker:
      - image: circleci/circleci-cli:0.1.29936
    working_directory: ~/workdir

  lint_job: &lint_job
    docker:
      - image: python:3.10.13-alpine3.19
    working_directory: ~/workdir

jobs:
  pack_and_validate:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Pack orb
          command: circleci config pack src > orb.yml
      - run:
          name: Validate orb
          command: circleci orb validate orb.yml
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - orb.yml

  publish_dev:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Publish orb as dev (deleted after 90 days)
          command: |
            if [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] ; then
              echo "Command skipped during 'Rerun job with SSH'"
              exit 0;
            fi
            circleci orb publish orb.yml codacy/base@dev:$(cat .version) --token $CIRCLE_TOKEN

  publish_prod:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Publish final orb
          command: |
            if [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] ; then
              echo "Command skipped during 'Rerun job with SSH'"
              exit 0;
            fi
            circleci orb publish orb.yml codacy/base@$(cat .version) --token $CIRCLE_TOKEN

  lint:
    <<: *lint_job
    steps:
      - checkout
      - run:
          name: setup yamllint
          command: |
            apk add --update py3-pip
            pip install --user yamllint
      - run:
          name: output default .yamllint file in the working directory
          command: |
            cat \<< EOF > .yamllint
            extends: relaxed
            rules:
              line-length:
                max: 200
                allow-non-breakable-inline-mappings: true
            EOF
      - run:
          name: yamllint
          command: python -m yamllint .

workflows:

  pack_validate_publish:
    jobs:
      - lint

      - codacy/checkout_and_version:
          name: checkout_and_version

      - pack_and_validate:
          context: CodacyCircleCI
          requires:
            - checkout_and_version
            - lint

      - codacy/tag_version:
          context: CodacyAWS
          name: tag_version
          requires:
            - pack_and_validate

      - publish_dev:
          context: CodacyCircleCI
          requires:
            - tag_version
          filters:
            branches:
              ignore:
                - master

      - publish_prod:
          context: CodacyCircleCI
          requires:
            - tag_version
          filters:
            branches:
              only:
                - master
