version: 2.1

orbs:
  codacy: codacy/base@dev:4.1.2-microk8sverify.21.9ce594c

references:
  circleci_job: &circleci_job
    docker:
      - image: circleci/circleci-cli:latest
    working_directory: ~/workdir

  lint_job: &lint_job
    docker:
      - image: singapore/lint-condo@sha256:b5edd1f14371b18d4446adc032348663acae8e6c65d0052a74d6ee1feb246107
    working_directory: ~/workdir

  helm_values: &helm_values
    microk8s_values_content: |
      global:
        imagePullSecrets:
          - name: docker-credentials
        play:
          cryptoSecret: "TEST_STRING"
        akka:
          sessionSecret: "TEST_STRING"
        filestore:
          contentsSecret: "TEST_STRING"
          uuidSecret: "TEST_STRING"
        cacheSecret: "TEST_STRING"
        codacy:
          crow:
            url: "http://localhost:9000"
      listener:
        persistence:
          claim:
            size: 8Gi
        nfsserverprovisioner:
          persistence:
            size: 10Gi
      minio:
        persistence:
          size: 10Gi
      rabbitmq-ha:
        replicaCount: 1

jobs:
  pack_and_validate:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Pack orb
          command: circleci config pack src > orb.yml
      - run:
          name: Validate orb
          command: circleci orb validate orb.yml
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - orb.yml

  publish_dev:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - deploy:
          name: Publish orb as dev (deleted after 90 days)
          command: circleci orb publish orb.yml codacy/base@dev:$(cat .version) --token $CIRCLE_TOKEN

  publish_prod:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - deploy:
          name: Publish final orb
          command: circleci orb publish orb.yml codacy/base@$(cat .version) --token $CIRCLE_TOKEN

  lint:
    <<: *lint_job
    steps:
      - checkout
      - run:
          name: output default .yamllint file in the working directory
          command: |
            cat \<< EOF > .yamllint
            extends: relaxed

            rules:
              line-length:
                max: 200
                allow-non-breakable-inline-mappings: true

            EOF
      - run:
          name: yamllint
          command: yamllint .

workflows:

  pack_validate_publish:
    jobs:
      # - codacy/microk8s_install:
      #     context: CodacyAWS
      #     name: install_k8s-1.15_helm-3.2
      #     helm_repo: "https://charts.codacy.com/stable"
      #     chart_version: "1.1.0"
      #     microk8s_channel: "1.15"
      #     helm_version: "v3.2.0"
      #     <<: *helm_values
      - lint

      - codacy/checkout_and_version:
          name: checkout_and_version

      - pack_and_validate:
          context: CodacyCircleCI
          requires:
            - checkout_and_version
            - lint

      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - pack_and_validate

      - publish_dev:
          context: CodacyCircleCI
          requires:
            - tag_version
          filters:
            branches:
              ignore:
                - master

      # - publish_prod:
      #     context: CodacyCircleCI
      #     requires:
      #       - tag_version
      #     filters:
      #       branches:
      #         only:
      #           - master
