version: 2.1

orbs:
  codacy: codacy/base@0.0.13

references:
  circleci_job: &circleci_job
    docker:
      - image: circleci/circleci-cli:0.1.5705
    working_directory: ~/workdir

jobs:
  pack_and_validate:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Pack orb
          command: circleci config pack src > orb.yml 
      - run:
          name: Validate orb
          command: circleci orb validate orb.yml
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir/orb.yml

  publish_dev:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/
      - deploy:
          name: Publish orb as dev (deleted after 90 days)
          command: circleci orb publish orb.yml codacy/base@dev:$(cat .version) --token $CIRCLE_TOKEN

  publish_prod:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/
      - deploy:
          name: Publish final orb
          command: circleci orb publish orb.yml codacy/base@$(cat .version) --token $CIRCLE_TOKEN

workflows:

  pack_validate_publish:
    jobs:
      - codacy/checkout_and_version

      - pack_and_validate:
          context: CodacyCircleCI
          requires:
          - codacy/checkout_and_version

      - codacy/tag_version:
          name: tag_version
          requires:
          - pack_and_validate

      - publish_dev:
          context: CodacyCircleCI
          requires:
          - tag_version
          filters:
            branches:
              ignore:
              - master

      - publish_prod:
          context: CodacyCircleCI
          requires:
          - tag_version
          filters:
            branches:
              only:
              - master
