version: 2.1

orbs:
  codacy: codacy/base@7.0.0

references:
  circleci_job: &circleci_job
    docker:
      - image: circleci/circleci-cli:0.1.5879
    working_directory: ~/workdir

  lint_job: &lint_job
    docker:
      - image: singapore/lint-condo@sha256:b5edd1f14371b18d4446adc032348663acae8e6c65d0052a74d6ee1feb246107
    working_directory: ~/workdir

jobs:
  pack_and_validate:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Pack orb
          command: circleci config pack src > orb.yml
      - run:
          name: Validate orb
          command: circleci orb validate orb.yml
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir/orb.yml

  publish_dev:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/
      - deploy:
          name: Publish orb as dev (deleted after 90 days)
          command: circleci orb publish orb.yml codacy/base@dev:$(cat .version) --token $CIRCLE_TOKEN

  publish_prod:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/
      - deploy:
          name: Publish final orb
          command: circleci orb publish orb.yml codacy/base@$(cat .version) --token $CIRCLE_TOKEN

  lint:
    <<: *lint_job
    steps:
      - checkout
      - run:
          name: output default .yamllint file in the working directory
          command: |
            cat \<< EOF > .yamllint
            extends: relaxed

            rules:
              line-length:
                max: 200
                allow-non-breakable-inline-mappings: true

            EOF
      - run:
          name: yamllint
          command: yamllint .

workflows:

  pack_validate_publish:
    jobs:
      - lint

      - codacy/checkout_and_version:
          name: checkout_and_version

      - pack_and_validate:
          context: CodacyCircleCI
          requires:
            - checkout_and_version
            - lint

      - codacy/tag_version:
          name: tag_version
          requires:
            - pack_and_validate

      - publish_dev:
          context: CodacyCircleCI
          requires:
            - tag_version
          filters:
            branches:
              ignore:
                - master

      - publish_prod:
          context: CodacyCircleCI
          requires:
            - tag_version
          filters:
            branches:
              only:
                - master
