version: 2.1

orbs:
  codacy: codacy/base@dev:4.1.2-microk8sverify.46.f8071c9

references:
  circleci_job: &circleci_job
    docker:
      - image: circleci/circleci-cli:latest
    working_directory: ~/workdir

  lint_job: &lint_job
    docker:
      - image: singapore/lint-condo@sha256:b5edd1f14371b18d4446adc032348663acae8e6c65d0052a74d6ee1feb246107
    working_directory: ~/workdir

  helm_values: &helm_values
    microk8s_values_content: |
      global:
        imagePullSecrets:
          - name: docker-credentials
        imagePullSecrets:
          - name: docker-credentials
        codacy:
          url: "https://localhost"
          backendUrl: "https://localhost"
        akka:
          sessionSecret: "e4AsBnEgWjfREd88mhULwdBojmjLJXWU5xusNZOZXX5cOANonRzXauSgMMZWwjMWdaJnTu6rzrZnopiPvpKwGaI1qHXDdGe2iUZVufXB6D2nJaDXAwKxVYSJD5ww5OpK7M3VhQpgDB6LGhAh4hdfE9mIHWFuBMWcDrdonYo"
        play:
          cryptoSecret: "Dwy2xw0Ycv5G4tC68vW3v1W2nQaPJSfaRv09i5bKC1oeESfUkuj2uVVkngC0yVHM01J1wMlZRfW3hzH3SvLuhDXKuAOpOSF5kdlZFcKfYGzU808w0meS48YYDF8TN1SqpzSjvw9N5l0UbbIhg0rPbL9njB3qx9mbvTGU"
        filestore:
          contentsSecret: "s0inkqKFKM7jTw0ctUJEKz6HZHGdax6nTZFvNy2ADN47mS9QTghqy6QEwJcB7qiXITD3hLTqnLUpmMtCHTs2SfffgXxGPFpuiTj3XDiCG1sTKqykhdpoooCsBZpbqfySaWvQ21OdAfVFYkauC8cbsq8ezdKJud2nBI"
          uuidSecret: "B7MrJaBp49IIB1wt4Yz31TPzj0hl24h0823Dge4Tn9pON9vjQl4OhsJNfsawRR0FG8mjm7aU4rEVD9fIupYBrGS5nD3fP7xfOX2wL6nYBVHh3pFLWIT7CwWHU9t5CDfJnmJsuwRNE3mhAIVkST4ZSCDERHXGj3S1p9JN40"
        cacheSecret: "vlWdrGm0TKdv4X66kXurTi7IJ1gQ0VrGj4yajWaGPciwsAPVovAJuQKtWmiNAXPQ4G06IASNJMio3lEcI4QG8cgfDL1xqbvxxAhhoB1kUmZB6DOcRIeMbcfzHaXg22xamyP1IlrvSADakIvCPlZ6lzoHhiTDKtQoSkcRY"
        codacy:
          crow:
            url: "http://localhost:9000"
      # activities:
      #   # Check how to re-enable this
      #   replicaCount: 0
      #   resources:
      #     limits:
      #       cpu: 1000m
      #       memory: 1500Mi
      #     requests:
      #       cpu: 100m
      #       memory: 1000Mi

      # codacy-api:
      #   replicaCount: 0
      #   resources:
      #     limits:
      #       cpu: 1000m
      #       memory: 2000Mi
      #     requests:
      #       cpu: 100m
      #       memory: 1000Mi

      # postgres:
      #   persistence:
      #     enabled: true
      #     size: 10Gi

      defaultdb:
        create: true
      analysisdb:
        create: true
      resultsdb:
        create: true
      metricsdb:
        create: true
      filestoredb:
        create: true
      jobsdb:
        create: true

      activities:
        activitiesdb:
          create: true

      crow:
        crowdb:
          create: true

      hotspots-api:
        hotspotsdb:
          create: true

      listener:
        persistence:
          claim:
            size: 2Gi
        nfsserverprovisioner:
          persistence:
            size: 3Gi
      minio:
        persistence:
          size: 2Gi
      rabbitmq-ha:
        replicaCount: 1

jobs:
  pack_and_validate:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Pack orb
          command: circleci config pack src > orb.yml
      - run:
          name: Validate orb
          command: circleci orb validate orb.yml
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - orb.yml

  publish_dev:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - deploy:
          name: Publish orb as dev (deleted after 90 days)
          command: circleci orb publish orb.yml codacy/base@dev:$(cat .version) --token $CIRCLE_TOKEN

  publish_prod:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - deploy:
          name: Publish final orb
          command: circleci orb publish orb.yml codacy/base@$(cat .version) --token $CIRCLE_TOKEN

  lint:
    <<: *lint_job
    steps:
      - checkout
      - run:
          name: output default .yamllint file in the working directory
          command: |
            cat \<< EOF > .yamllint
            extends: relaxed

            rules:
              line-length:
                max: 200
                allow-non-breakable-inline-mappings: true

            EOF
      - run:
          name: yamllint
          command: yamllint .

workflows:

  pack_validate_publish:
    jobs:
      # - codacy/microk8s_install:
      #     context: CodacyAWS
      #     name: install_k8s-1.15_helm-3.2
      #     helm_repo: "https://charts.codacy.com/stable"
      #     chart_version: "1.0.1"
      #     microk8s_channel: "1.15"
      #     helm_version: "v3.2.0"
      #     <<: *helm_values
      - lint

      - codacy/checkout_and_version:
          name: checkout_and_version

      - pack_and_validate:
          context: CodacyCircleCI
          requires:
            - checkout_and_version
            - lint

      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - pack_and_validate

      - publish_dev:
          context: CodacyCircleCI
          requires:
            - tag_version
          filters:
            branches:
              ignore:
                - master

      # - publish_prod:
      #     context: CodacyCircleCI
      #     requires:
      #       - tag_version
      #     filters:
      #       branches:
      #         only:
      #           - master
