parameters:
  qa_automation_runner_version:
    description: "The qa-automation-tests version to use"
    type: string

docker:
  - image: codacy/qa-automation-test-runner:<< parameters.qa_automation_runner_version >>
  - image: selenium/standalone-chrome:3.141.0
